---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    author: mel
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
      author: mel
...
