---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    author: mel
 spec:
   containers:
     - name: redis
       image: redis
       ports:
         - containerPort: 6379
...