---
apiVersion: v1
kind: pod
metadata:
  name: result-app-pod
  labels:
    name: result-app
    author: mel
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
...

