---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    author: mel
spec:
  type: loadBalancer
  ports:
    - port: 80
      targetPort: 80
selector:
  author: mel
    name: voting-app-pod